// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	engineInfo: () => __TAURI_INVOKE<EngineInfo>("engine_info"),
};

/* Types */
/**
 *  Build information the shell and MCP status surfaces report. Also the
 *  pipeline probe for T-105: its round-trip into `ui/` proves the generated
 *  bindings work end to end.
 */
export type EngineInfo = {
	app_version: string,
};

